### ISSUE TITLE
An "Updatable" base class to handle entities to update by using some "UpdateModule".

### ISSUE THREAD

**Issue by CBenoit** [Mirai-Team/mirai-project#13]
For instance, I want to create monsters in my game. All monsters could be updated by a "monsters update module" by calling a single method. And every single monster (modelized by a class called "Monster" which is a "Updatable" child class) is automatically added to the "monster update module" when created.

**Comment by Lomadriel** [comment]
It's done in Updatable2 branch. I have to add documentation and we can pull.

**Comment by Lomadriel** [comment]
Documentation add. Merge in https://github.com/Mirai-Team/mirai-project/pull/22

**Comment by CBenoit** [comment]
The current UpdateModule class doesn't allow to update different group of Updatable objects.
For instance, an update module only for characters and an update module only for items. Or something like that.
