### ISSUE TITLE
Add an InputManager system

### ISSUE THREAD

**Issue by Lomadriel** [Mirai-Team/mirai-project#33]
- [x] Keyboard Manager
- [x] Mouse Manager
- [x] Combination keys binding.
- [x] A way of calling the function on key released, on key pressed and while key pressed.

**Comment by Lomadriel** [comment]
Mouse and Keyboard manager done.

**Comment by Lomadriel** [comment]
The last point is almost done. But I have to create a way for key pressed.

**Comment by CBenoit** [comment]
Just create a member boolean called "isPressed_" in Binding class, if 'isPressed_' is false you can call the function for the on key pressed mode just before set "isPressed_" to true. When you set again "isPressed_" to false, you can call the function for the on key released mode. If none of theses modes are selected. Just do as usual, always call the function.

**Comment by Lomadriel** [comment]
This is what I did. ^^

It was something else but It's corrected now.

**Comment by CBenoit** [comment]
I checked it, everything alright ! :)
Just had to update some things in the in-code documentation.
