### ISSUE TITLE
Add an Event Manager

### ISSUE THREAD

**Issue by Lomadriel** [Mirai-Team/mirai-project#38]
Allows you to run a function in a class according to an action from another class.
(Listener and Notifier system)
- [x] no parameters
- [x] with parameters

**Comment by Lomadriel** [comment]
Done in EventManager branch but I have some warning in EventManager.hpp and I don't know how to remove them.

**Comment by Lomadriel** [comment]
I think it's a bug from gcc

**Comment by Lomadriel** [comment]
I use a derivation of Keyboard Manager system but the key is replaced by a event.

**Comment by Lomadriel** [comment]
https://github.com/Mirai-Team/mirai-project/commit/35dba87ddc53a9b2ab6e9eeb5872155e1ce59824

**Comment by CBenoit** [comment]
I assume that the system is pretty similar to the InputManager part, so I would like to signal exactly the same thing that I said for issue https://github.com/Mirai-Team/mirai-project/issues/43 about parameters.

**Comment by Lomadriel** [comment]
nop. It's no the same thing. AddListener(string, function). Broadcast(string, param...)

**Comment by Lomadriel** [comment]
Added with parameter in EventManager2. Need a overhaul but it's functional.

**Comment by CBenoit** [comment]
Exemple not compiling on my computer : 

```
[ 77%] Built target EncryptionExample
[ 80%] Building CXX object examples/eventManager/CMakeFiles/EventManagerExample.dir/src/main.cpp.o
In file included from /home/benoit/Dev/mirai-project/include/MiraiProject/eventManager/EventManager.hpp:111:0,
                 from /home/benoit/Dev/mirai-project/examples/eventManager/src/main.cpp:28:
/home/benoit/Dev/mirai-project/include/MiraiProject/eventManager/EventManager.tpp: In member function ‘T mp::EventManager::broadcast(std::string, Args ...) [with T = int; Args = {int}; std::string = std::basic_string<char>]’:
/home/benoit/Dev/mirai-project/include/MiraiProject/eventManager/EventManager.tpp:52:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
```

**Comment by Lomadriel** [comment]
Hum, you have only quoted a warning. So I don't know why the compilation fails.

But I want to update the example which is quite useless.

**Comment by Lomadriel** [comment]
Done

**Comment by CBenoit** [comment]
Uh, yes, It was just a warning and the executable was produced in fact. I didn't seen it at the moment.

The new example is better, but you should define Player class in another file like Monster.

About the EventManager class : 
There is probably a way to replace
`static std::shared_ptr<EventManager> instance_;`
by
`static EventManager instance_;`
Here https://github.com/Mirai-Team/mirai-project/blob/EventManager2/include/MiraiProject/eventManager/EventManager.hpp#L105

Then, you simply return a reference here : https://github.com/Mirai-Team/mirai-project/blob/EventManager2/include/MiraiProject/eventManager/EventManager.hpp#L47

Like in WindowManager class : https://github.com/Mirai-Team/mirai-project/blob/EventManager2/include/MiraiProject/util/WindowManager.hpp

It is better to not use pointers if possible.

**Comment by Lomadriel** [comment]
In this case we can't, it's a singleton pattern. Indeed there is a singleton pattern with reference but unsafe so I think it's better to use pointer

**Comment by Lomadriel** [comment]
This message replace the previous one. Indeed we can. But I don't if gcc supports it. I check it and if gcc support it. I do it.

**Comment by CBenoit** [comment]
I see no reason this way could works only for the very case of the WindowManager and not for this one. And why it would be unsafe to do it here ?

**Comment by Lomadriel** [comment]
WindowManager isn't singleton but I have to find a way to keep this class singleton and thread-safe.

**Comment by CBenoit** [comment]
But you can still return a reference.
Using the shared_ptr is thread-safe ?

**Comment by Lomadriel** [comment]
If I return a reference like you do in WindowManager class, this class will no longer be singleton.

**Comment by CBenoit** [comment]
A reference isn't a copy, but an hidden pointer to the same instance. So I don't see why this is no longer a singleton.

**Comment by Lomadriel** [comment]
I know that but it's a little bit more complicated. I can do it like in WindowManager but if I do it the class is "singleton" but absolutely not thread-safe.
