### ISSUE TITLE
Update base encryption

### ISSUE THREAD

**Issue by Lomadriel** [Mirai-Team/mirai-project#52]
In encryption class, I think it's better to use (unsigned char*) instead std::string, indeed char is one byte type. Moreover hold a pointer is better than hold the whole file

**Comment by Lomadriel** [comment]
See #66

**Comment by Lomadriel** [comment]
I think we should also remove boost::filesystem from MP before accept the pr #66. It's quite easy to remove it since we just list all the files in the given directory.

**Comment by CBenoit** [comment]
Yes, so users no longer needs to have boost::filesystem, if he's not interested in it.

**Comment by Lomadriel** [comment]
See #79

**Comment by Lomadriel** [comment]
Since the Archiver + basic encryption functions were accepted, I close this issue.
