### ISSUE TITLE
Clickable widget hitbox

### ISSUE THREAD

**Issue by Lomadriel** [Mirai-Team/mirai-project#53]
We should add a hitbox support for clickable widget. Moreover maybe support a detection of sf::Color::Transparent and set this color as non-clickable.

**Comment by CBenoit** [comment]
Definitly possible !
`myTexture.copyToImage().getPixel(x, y);`

http://www.sfml-dev.org/documentation/2.2-fr/classsf_1_1Texture.php#aefc19bcd95565dd2348fd4cec0facddc
http://www.sfml-dev.org/documentation/2.2-fr/classsf_1_1Image.php#a8c8460e311dcb00557cb00a81c29163d

**Comment by Lomadriel** [comment]
I have work on it and it's done. See #54
