### ISSUE TITLE
Encryption system, writeHeader

### ISSUE THREAD

**Issue by Lomadriel** [Mirai-Team/mirai-project#8]
The file path isn't cross platform. We can't find a file on Windows.

**Comment by Lomadriel** [comment]
Normally it works. Just test it under windows.

**Comment by CBenoit** [comment]
Got encryption example works under Windows, however I had warning while compiling FileUtilities.cpp file : 

```
[...]mirai_project\src\util\FilesUtilities.cpp:67:8: warning: "__uni
x__" is not defined [-Wundef]
  #elif __unix__
          ^
```

**Comment by CBenoit** [comment]
Problem solved : https://github.com/Mirai-Team/mirai-project/commit/a6590dbddd356cc7ac8fb6904fbb665c5ec22851
